apiVersion: apps/v1
kind: Deployment
metadata:
  name: expenseapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expenseapp
  template:
    metadata:
      labels:
        app: expenseapp
    spec:
      containers:
        - name: expenseapp
          image: snehcreate/expensetracker_v3
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/expense_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              value: expense_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: expense_pass
---
apiVersion: v1
kind: Service
metadata:
  name: expenseapp-service
spec:
  type: NodePort
  selector:
    app: expenseapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007

